### ISSUE TITLE
Blinking spawn process on Windows

### ISSUE THREAD

**Issue by gavr123456789** [benwaffle/vala-language-server#120]
**Describe the bug**
Each update of the project symbols causes the opening and closing processes to blink. They take over the focus that interrupts autocomplete.  
I think its symbol extractor.

**Software**
OS and version (e.g. Ubuntu 20.04): Windows
Code editor (e.g. VSCode): VSCode
Vala Language Server (e.g. git commit, or PPA/AUR version): 0.48
Vala version (`valac --version`): 0.48.6

https://youtu.be/r3sY2NzDyiI

A temporary solution may be the ability to disable it in the client settings.

**Comment by Prince781** [comment]
I don't see how this has anything to do with VLS.

**Comment by gavr123456789** [comment]
@taozuhong do you have something similar?

**Comment by taozuhong** [comment]
yeah, me too. it's serious for the user.
Step 1. Enable extension, restart vscode, open project, cmd.exe window splashed twice
Step 2. Open a vala file, cmd.exe window splashed twice again.
Step 3. Input word chars, like: m_tab_work_books, while input the underline(_), wait about one second, cmd.exe window splashed twice again; repeat this as follows.
It will disappear while input chars continually, that's it.

BTW, I am tracking the change of VLS every day, but not yet use it in my project(using vala extension), because vala-code does not implement the template and context autocomplete of vala file.

fighting, friends.

**Comment by gavr123456789** [comment]
I think here it is  
https://github.com/benwaffle/vala-language-server/blob/bd64b248fd94fc8ed1dd6a6d29f2e8ffc4c20bda/src/projects/mesonproject.vala#L148

**Comment by Prince781** [comment]
Hmm..there does seem to be a problem with path resolution under Windows, caused by https://github.com/benwaffle/vala-language-server/commit/0aa20ba951db6a9ce246610eafaea2cb2dfaa341

**Comment by Prince781** [comment]
When I said VLS doesn't spawn a process for completion, that was correct. It does however spawn processes when initially setting up the Meson project. Perhaps issues with path resolution on Windows are causing the Meson project setup to be run multiple times.

**Comment by Prince781** [comment]
@gavr123456789 @taozuhong tell me if https://github.com/benwaffle/vala-language-server/pull/121 fixes your issue (checkout the branch `bug/windows-path-resolution`)

**Comment by taozuhong** [comment]
not yet, same as master version.

**Comment by gavr123456789** [comment]
This is fun
```bash

Found ninja.EXE-1.10.0 at C:\msys64\mingw64\bin/ninja.EXE

ERROR: Clock skew detected. File C:/msys64/home/gavr/vala-language-server-bug-windows-path-resolution/build/../meson.build has a time stamp 9665.5390s in the future.

A full log can be found at C:/msys64/home/gavr/vala-language-server-bug-windows-path-resolution/build/meson-logs/meson-log.txt

```

**Comment by Prince781** [comment]
Okay, so this issue isn't fixed, but is the issue with dependencies fixed?

**Comment by Prince781** [comment]
It seems the issues with dependencies on Windows are also fixed by the commit. However, I wasn't abl to reproduce the stuttering/flickering. 

![see here](https://i.imgur.com/Omwifwj.gif)

**Comment by taozuhong** [comment]
this is the screen recorder of vscode under MSYS2
[vscode.zip](https://github.com/benwaffle/vala-language-server/files/4720751/vscode.zip)

**Comment by Prince781** [comment]
https://imgur.com/03oj3bx.png

@taozuhong, from this frame, it looks like what's being run is `pkg-config`. As VLS does not run `pkg-config` directly, this is done by the Vala compiler when checking for deprecated symbols.

Just curious, are you able to downgrade to Vala 0.48.3 on your MinGW installation? If so, then try running VLS with your project.

**Comment by Prince781** [comment]
@taozuhong @gavr123456789 Just to be clear, I think the behavior you're seeing is a result of Vala doing the right thing now, after a bug fix that I made for a separate issue. It seems that this might also be a new issue that was exposed. A temporary workaround right now might be to add `--disable-since-check` as a flag to all of the targets in your build system like below (for Meson):

```meson
if host_machine.system() == 'windows'
    # disable since check on Windows
    add_project_arguments(['--disable-since-check'], language: 'vala')
endif
```

**Comment by Prince781** [comment]
@taozuhong @gavr123456789 you can try downgrading to a Vala version before 0.48.3 by looking in `/var/cache/pacman/pkg`, where previously-installed packages are cached.

**Comment by taozuhong** [comment]
Exactly right, the Vala 0.48.3 is silent, and just splash the cmd.exe window once(not yet add the flag you mentioned).

**Comment by taozuhong** [comment]
the experience of VSCode on windows is back to bad again:
crashed, window flash, responsible slowly

I have to disable it. do you try it on windows?

**Comment by Prince781** [comment]
@taozuhong I test VLS on Linux and Windows, but I develop most of the time on Linux. I make sure to periodically test VLS on Windows after certain changes that I think might cause problems.

**Comment by Prince781** [comment]
@taozuhong can you post the output of VLS?

**Comment by Prince781** [comment]
@taozuhong There shouldn't be any crashes in VLS. I just test-ran the master branch with updated MSYS packages and there are no crashes. But there are issues with spawning Meson and of course there's still the issue with console windows being created when spawning subprocesses.

**Comment by taozuhong** [comment]
pls keep up making a great experience.

**Comment by gavr123456789** [comment]
So, we have to start doing something. I'm not sure if I need to create an issue in Vala or GLib. This is a very serious problem, VLS is not usable under windows as long as it exists.

**Comment by Prince781** [comment]
@gavr123456789 Agreed. After testing this with other programs that use GLib I've concluded this is a problem with how GLib spawns processes on Windows. The ultimate fix lies there, but perhaps if it takes too long to be fixed I could come up with a temporary hack in VLS that would minimize the problem (but not make it go away completely).

**Comment by Prince781** [comment]
@gavr123456789 I have an idea of how to fix this in GLib. Right now I'm finishing up symbol rename support with some edge-cases. Give me a few days to start working on this issue.

**Comment by Prince781** [comment]
Just letting you know I haven't forgotten about this issue. I've opened a MR in GLib that I think will solve it:

https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1662

**Comment by gavr123456789** [comment]
Just checked win32 workaround branch, it doesnt help, still blinking.

**Comment by gavr123456789** [comment]
![Peek 2020-10-09 17-52](https://user-images.githubusercontent.com/30507409/95598192-4f5fa480-0a58-11eb-9ca3-49c6ecfad423.gif)

**Comment by Prince781** [comment]
@gavr123456789 the win32-workaround branch only helps with launching `meson` from VLS. It doesn't change what libvala does with `pkg-config`.

If you want to test the fix in the patch, you can do these steps in msys2:

1. clone the [MINGW-packages](https://github.com/msys2/MINGW-packages) repository
```
git clone https://github.com/msys2/MINGW-packages
```
2. from msys2 terminal, install `patch`
3. then cd into `MINGW-packages/mingw-w64-glib2`
4. then edit the `PKGBUILD`, changing the first value in `source=(...)` to `git+https://gitlab.gnome.org/Prince781/glib`. At the same time, make sure to set the first hash value in `sha256sums=(...)` array to `'SKIP'`
5. then change all instances of `${srcdir}/glib-${pkgver}` to `${srcdir}/glib` in the PKGBUILD
6. then in the `prepare() { ... }` function add the following line:
```
git checkout wip/prince781/fix-gspawn-terminal-win32
```
7. finally, build the package by running `makepkg -s`

Or you can just apply this patch instead of steps 4-6:
https://gist.github.com/Prince781/f526b5e5a379f365776851214639c8c5

Also, I've already built this package, so you can try installing it from here: https://www.dropbox.com/s/oofngh6z897y471/mingw-w64-x86_64-glib2-2.66.1-1-any.pkg.tar.zst

**Comment by gavr123456789** [comment]
![Peek 2020-10-09 20-44](https://user-images.githubusercontent.com/30507409/95615219-8cd02c00-0a70-11eb-8f10-0f007481bbd1.gif)
Ty, that woks!  (that glitch only on record)
(for others, just `pacman -U ....zst`)

**Comment by Prince781** [comment]
> Just letting you know I haven't forgotten about this issue. I've opened a MR in GLib that I think will solve it:
> 
> https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1662

While this MR is still in progress, I've rebuilt `mingw-w64-x86_64-glib2` with the latest version of GLib and the patch. You can get it here:
[mingw-w64-x86_64-glib2-2.68.1-1-any.pkg.tar.zip](https://github.com/benwaffle/vala-language-server/files/6332213/mingw-w64-x86_64-glib2-2.68.1-1-any.pkg.tar.zip)

**Comment by Prince781** [comment]
My PR has been merged into GLib upstream. I think I can close this bug. Until the latest version of GLib lands in MinGW you can use the package I've built.

**Comment by Project-Magenta** [comment]
Thank you
